### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by jackprophesy** [ZestFinance/zestphone#4]
$ bundle exec rake app:db:create:all
telephony_development already exists
telephony_test already exists
telephony_test already exists
telephony_test already exists
telephony_development already exists
telephony_test already exists

$  bundle exec rake app:db:migrate
No such file or directory - 
zestphone/spec/dummy/config/call_centers.yml

**Comment by jhl-zest** [comment]
Hi jackmcgary - our apologies for the cryptic / poorly written instructions!  we've recently rewritten our readme and our setup instructions.  If you're still interested, please take another look and let me know if these instructions are helpful - thanks -
